/*
 * LogoffRequestMessage.hpp
 *
 *  Created on: 23-Jul-2016
 *      Author: ankithbti
 */

#ifndef ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_LOGOFFREQUESTMESSAGE_HPP_
#define ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_LOGOFFREQUESTMESSAGE_HPP_





#endif /* ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_LOGOFFREQUESTMESSAGE_HPP_ */
