/*
 * UpdateLocalDBRequestMessage.hpp
 *
 *  Created on: 23-Jul-2016
 *      Author: ankithbti
 */

#ifndef ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_UPDATELOCALDBREQUESTMESSAGE_HPP_
#define ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_UPDATELOCALDBREQUESTMESSAGE_HPP_





#endif /* ORDERMANAGEMENTSYSTEM_INCLUDE_ADAPTORLAYER_MSG_OUTGOING_UPDATELOCALDBREQUESTMESSAGE_HPP_ */
